name: LemonadeStand
version: '${version}'
main: org.empirewar.lemonadestand.LemonadeStand
api-version: 1.19
authors: [ StealWonders ]
description: Accept incoming Ko-Fi webhooks and allow further processing.
